name: "Build and Push Image to Ryvn Registry"
description: "Builds a Docker image and pushes it to Ryvn Registry"

inputs:
  service_name:
    description: "Name of the service"
    required: true
  version:
    description: "Semantic version to tag the image with"
    required: true
  build_only:
    description: "Build the image only, don't push it to registry"
    required: false
    default: "false"
  ryvn_client_id:
    description: "Ryvn Client ID for authentication"
    required: true
  ryvn_client_secret:
    description: "Ryvn Client Secret for authentication"
    required: true
  build_args:
    description: "Build arguments to pass to the Docker build"
    required: false

runs:
  using: "composite"
  steps:
    - name: Install Ryvn CLI
      uses: ryvn-technologies/install-ryvn-cli@v1.0.0

    - name: Get Service and Registry Details from Ryvn API
      id: service
      shell: bash
      env:
        RYVN_CLIENT_ID: ${{ inputs.ryvn_client_id }}
        RYVN_CLIENT_SECRET: ${{ inputs.ryvn_client_secret }}
      run: |
        # Get service details
        ryvn get service ${{ inputs.service_name }} -o json > service.json

        echo "Service details: $(cat service.json)"

        # Extract and validate working directory
        working_dir=$(jq -r '.definition.build.workingDir' service.json)
        if [ "$working_dir" = "null" ] || [ -z "$working_dir" ]; then
          echo "Error: working_dir not found in service definition"
          exit 1
        fi

        # Extract and validate dockerfile path
        dockerfile_path=$(jq -r '.definition.build.dockerfilePath' service.json)
        if [ "$dockerfile_path" = "null" ] || [ -z "$dockerfile_path" ]; then
          echo "Error: dockerfile_path not found in service definition"
          exit 1
        fi

        # Extract and validate image name
        image_name=$(jq -r '.definition.imageName' service.json)
        if [ "$image_name" = "null" ] || [ -z "$image_name" ]; then
          echo "Error: imageName not found in service definition"
          exit 1
        fi

        # Extract and validate orgId
        org_id=$(jq -r '.definition.orgId' service.json)
        if [ "$org_id" = "null" ] || [ -z "$org_id" ]; then
          echo "Error: orgId not found in service definition"
          exit 1
        fi

        # Set static registry values
        registry_url="703671917981.dkr.ecr.us-east-1.amazonaws.com"
        role_arn="arn:aws:iam::703671917981:role/${org_id}-github-actions"
        region="us-east-1"

        # Set outputs
        echo "working_dir=$working_dir" >> $GITHUB_OUTPUT
        echo "dockerfile_path=$dockerfile_path" >> $GITHUB_OUTPUT
        echo "registry_url=$registry_url" >> $GITHUB_OUTPUT
        echo "role_arn=$role_arn" >> $GITHUB_OUTPUT
        echo "region=$region" >> $GITHUB_OUTPUT
        echo "image_name=$image_name" >> $GITHUB_OUTPUT

    - name: Configure AWS credentials
      if: inputs.build_only != 'true'
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ steps.service.outputs.role_arn }}
        aws-region: ${{ steps.service.outputs.region }}

    - name: Login to Amazon ECR
      if: inputs.build_only != 'true'
      uses: aws-actions/amazon-ecr-login@v2

    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ steps.service.outputs.registry_url }}/${{ steps.service.outputs.image_name }}
        tags: |
          type=semver,pattern={{version}},value=${{ inputs.version }}
          type=sha
          type=ref,event=pr

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ${{ steps.service.outputs.working_dir }}
        file: ${{ steps.service.outputs.dockerfile_path }}
        push: ${{ inputs.build_only != 'true' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: ${{ inputs.build_args }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

branding:
  icon: "package"
  color: "blue"
