name: "Build and Push to Ryvn Registry"
description: "Builds and pushes Docker images or Helm charts to Ryvn Registry"

inputs:
  service_name:
    description: "Name of the service"
    required: true
  version:
    description: "Semantic version to tag the image/chart with"
    required: true
  build_only:
    description: "Build only, don't push to registry"
    required: false
    default: "false"
  ryvn_client_id:
    description: "Ryvn Client ID for authentication"
    required: true
  ryvn_client_secret:
    description: "Ryvn Client Secret for authentication"
    required: true
  build_args:
    description: "Build arguments to pass to the Docker build"
    required: false

runs:
  using: "composite"
  steps:
    - name: Install Ryvn CLI
      uses: ryvn-technologies/install-ryvn-cli@v1.0.0

    - name: Get Service and Registry Details from Ryvn API
      id: service
      shell: bash
      env:
        RYVN_CLIENT_ID: ${{ inputs.ryvn_client_id }}
        RYVN_CLIENT_SECRET: ${{ inputs.ryvn_client_secret }}
      run: |
        # Get service details
        ryvn get service ${{ inputs.service_name }} -o json > service.json

        echo "Service details: $(cat service.json)"

        # Extract and validate service type
        service_type=$(jq -r '.definition.type' service.json)
        if [ "$service_type" = "null" ] || [ -z "$service_type" ]; then
          echo "Error: service type not found in service definition"
          exit 1
        fi

        # Extract and validate working directory
        working_dir=$(jq -r '.definition.build.workingDir' service.json)
        if ([ "$working_dir" = "null" ] || [ -z "$working_dir" ]) && [ "$service_type" = "web-server.v1" ]; then
          echo "Error: working_dir not found in service definition"
          exit 1
        fi

        # Extract and validate dockerfile path
        dockerfile_path=$(jq -r '.definition.build.dockerfilePath' service.json)
        if ([ "$dockerfile_path" = "null" ] || [ -z "$dockerfile_path" ]) && [ "$service_type" = "web-server.v1" ]; then
          echo "Error: dockerfile_path not found in service definition"
          exit 1
        fi

        # Extract and validate image name
        image_name=$(jq -r '.definition.imageName' service.json)
        if ([ "$image_name" = "null" ] || [ -z "$image_name" ]) && [ "$service_type" = "web-server.v1" ]; then
          echo "Error: imageName not found in service definition"
          exit 1
        fi

        # Extract and validate helm chart path
        helm_chart_path=$(jq -r '.definition.build.chartPath' service.json)
        if ([ "$helm_chart_path" = "null" ] || [ -z "$helm_chart_path" ]) && [ "$service_type" = "helm-chart.v1" ]; then
          echo "Error: chartPath not found in service definition"
          exit 1
        fi

        # Extract chart name
        chart_name=$(jq -r '.definition.chartName' service.json)
        if ([ "$chart_name" = "null" ] || [ -z "$chart_name" ]) && [ "$service_type" = "helm-chart.v1" ]; then
          echo "Error: chartName not found in service definition"
          exit 1
        fi

        # Extract and validate orgId
        org_id=$(jq -r '.orgId' service.json)
        if [ "$org_id" = "null" ] || [ -z "$org_id" ]; then
          echo "Error: orgId not found in service definition"
          exit 1
        fi

        # Set static registry values
        registry_url="703671917981.dkr.ecr.us-east-1.amazonaws.com"
        role_arn="arn:aws:iam::703671917981:role/${org_id}-github-actions"
        region="us-east-1"

        # Set outputs
        echo "service_type=$service_type" >> $GITHUB_OUTPUT
        echo "helm_chart_path=$helm_chart_path" >> $GITHUB_OUTPUT
        echo "chart_name=$chart_name" >> $GITHUB_OUTPUT
        echo "working_dir=$working_dir" >> $GITHUB_OUTPUT
        echo "dockerfile_path=$dockerfile_path" >> $GITHUB_OUTPUT
        echo "registry_url=$registry_url" >> $GITHUB_OUTPUT
        echo "role_arn=$role_arn" >> $GITHUB_OUTPUT
        echo "region=$region" >> $GITHUB_OUTPUT
        echo "image_name=$image_name" >> $GITHUB_OUTPUT

    - name: Configure AWS credentials
      if: inputs.build_only != 'true'
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ steps.service.outputs.role_arn }}
        aws-region: ${{ steps.service.outputs.region }}

    - name: Login to Amazon ECR
      if: inputs.build_only != 'true'
      uses: aws-actions/amazon-ecr-login@v2

    # Docker Image Steps
    - name: Extract Docker metadata
      if: steps.service.outputs.service_type == 'web-server.v1'
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ steps.service.outputs.registry_url }}/${{ steps.service.outputs.image_name }}
        tags: |
          type=semver,pattern={{version}},value=${{ inputs.version }}
          type=sha
          type=ref,event=pr

    - name: Set up Docker Buildx
      if: steps.service.outputs.service_type == 'web-server.v1'
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      if: steps.service.outputs.service_type == 'web-server.v1'
      uses: docker/build-push-action@v5
      with:
        context: ${{ steps.service.outputs.working_dir }}
        file: ${{ steps.service.outputs.dockerfile_path }}
        push: ${{ inputs.build_only != 'true' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: ${{ inputs.build_args }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    # Helm Chart Steps
    - name: Install Helm
      if: steps.service.outputs.service_type == 'helm-chart.v1'
      uses: azure/setup-helm@v3
      with:
        version: v3.12.1

    - name: Package Helm Chart
      if: steps.service.outputs.service_type == 'helm-chart.v1'
      shell: bash
      run: |
        cd ${{ steps.service.outputs.helm_chart_path }}
        helm package . --version ${{ inputs.version }}

    - name: Push Helm Chart to Registry
      if: steps.service.outputs.service_type == 'helm-chart.v1' && inputs.build_only != 'true'
      shell: bash
      run: |
        helm push ${{ steps.service.outputs.chart_name }}-${{ inputs.version }}.tgz oci://${{ steps.service.outputs.registry_url }}/${{ steps.service.outputs.image_name }}

branding:
  icon: "package"
  color: "blue"
